[package]
name = "rust_containers"
version = "0.1.0"
edition = "2024"


[dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
rand = "0.9.2"


[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "std_containers"
harness = false

